name: clinica_visionex
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.10.0
  google_fonts: ^6.1.0
  flutter_stripe: ^12.0.2
  # Dependencias para el test - versiones compatibles
  camera: ^0.11.0
  google_mlkit_face_detection: ^0.11.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.1
  string_similarity: ^2.0.0
  diacritic: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo.png
    - assets/imagenes/ishihara/